---
title: "VolcanoPlots"
author: "Christina Schmidt"
date: "17 March 2021"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
editor_options:
  chunk_output_type: console
---
```{r, warning=FALSE, message=FALSE}
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function

library(wakefield)#to generate vector of random names

library(ggrepel)
library(EnhancedVolcano)#volcanoPlot package
```

# General Plot
input data includes column "Log2FC" and "p.adj".
```{r}
VolcanoPlot_General <- function(Input, Omics, OutputName){
  VolcanoPlot <- EnhancedVolcano (Input,
                lab = paste("Input$", Omics),#Metabolite name
                x = "Log2FC",#Log2FC
                y = "p.adj",#p-value or q-value
                xlab = "Log2FC",
                ylab = bquote(~-Log[10]~`p.adj`),#(~-Log[10]~adjusted~italic(P))
                pCutoff = 0.9,
                FCcutoff = 0.01,#Cut off Log2FC, automatically 2
                pointSize = 4,
                labSize = 1,
                titleLabSize = 16,
                col=c("black", "grey", "grey", "red"),#if you want to change colors
                colAlpha = 0.5,
                title=paste(OutputName),
                subtitle = paste(Omics),
                caption = paste0("total = ", nrow(Input)/2, " ", Omics),
                xlim = c((((Reduce(min,Input$Log2FC))))-0.5,(((Reduce(max,Input$Log2FC))))-0.5),
                ylim = c(0,((-log10(Reduce(min,Input$p.adj))))+0.1),
                #drawConnectors = TRUE,
                #widthConnectors = 0.5,
                #colConnectors = "black",
                cutoffLineType = "dashed",
                cutoffLineCol = "black",
                cutoffLineWidth = 0.5,
                legendPosition = 'right',
                legendLabSize = 12,
                legendIconSize = 5.0
                )
  ggsave(file=paste("Output_Figures/VolcanoPlot_General", OutputName, ".pdf", sep="_"), plot=VolcanoPlot, width=10, height=8)
 plot(VolcanoPlot)
}

# Make an example DF:
Gene <- name(300)
Log2FC <- runif(300, min=-5, max=5)
p.adj <- runif(300, min=0, max=1)

DF_Input <- data.frame(Gene, Log2FC, p.adj, stringsAsFactors=FALSE)

# Make the plot
VolcanoPlot_General(Input=DF_Input,
                    Omics="Gene",
                    OutputName="RNAseq_01.05.2020")
```

# Information about packge used and versions 
```{r}
sessionInfo()
```
